export const seedExercises = [
  // 가슴 (chest) - 13개
  {
    name_ko: '바벨 벤치 프레스',
    name_en: 'Barbell Bench Press',
    category: 'chest' as const,
    equipment: 'barbell' as const,
    description: '평평한 벤치에 누워 바벨을 가슴 위로 밀어 올리는 가슴 운동의 기본 종목',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근', '삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 벤치 프레스',
    name_en: 'Dumbbell Bench Press',
    category: 'chest' as const,
    equipment: 'dumbbell' as const,
    description: '평평한 벤치에 누워 덤벨을 양손에 들고 밀어 올리며 가슴 근육의 균형 발달을 돕는 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근', '삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '인클라인 덤벨 프레스',
    name_en: 'Incline Dumbbell Press',
    category: 'chest' as const,
    equipment: 'dumbbell' as const,
    description: '경사진 벤치에서 덤벨을 밀어 올려 윗가슴을 타겟으로 하는 운동',
    primary_muscles: ['대흉근 상부'],
    secondary_muscles: ['전면 삼각근', '삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 플라이',
    name_en: 'Dumbbell Fly',
    category: 'chest' as const,
    equipment: 'dumbbell' as const,
    description: '벤치에 누워 덤벨을 양옆으로 벌렸다가 모으며 가슴 근육을 스트레칭하는 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '케이블 크로스오버',
    name_en: 'Cable Crossover',
    category: 'chest' as const,
    equipment: 'cable' as const,
    description: '케이블 머신을 이용해 가슴 중앙을 집중적으로 수축시키는 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '딥스',
    name_en: 'Dips',
    category: 'chest' as const,
    equipment: 'bodyweight' as const,
    description: '평행봉에 몸을 지탱하고 상체를 숙였다가 올리며 가슴 하부와 삼두근을 발달시키는 운동',
    primary_muscles: ['대흉근 하부', '삼두근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '머신 체스트 프레스',
    name_en: 'Machine Chest Press',
    category: 'chest' as const,
    equipment: 'machine' as const,
    description: '머신을 이용해 안정적으로 가슴 근육을 자극하는 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근', '삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '푸시업',
    name_en: 'Push-up',
    category: 'chest' as const,
    equipment: 'bodyweight' as const,
    description: '바닥에 엎드려 팔을 펴며 몸을 들어올리는 기본 가슴 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['삼두근', '전면 삼각근', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '디클라인 벤치 프레스',
    name_en: 'Decline Bench Press',
    category: 'chest' as const,
    equipment: 'barbell' as const,
    description: '하향 경사진 벤치에서 바벨을 밀어 올려 가슴 하부를 집중 타겟하는 운동',
    primary_muscles: ['대흉근 하부'],
    secondary_muscles: ['삼두근', '전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '펙덱 플라이',
    name_en: 'Pec Deck Fly',
    category: 'chest' as const,
    equipment: 'machine' as const,
    description: '펙덱 머신에 앉아 팔을 모으며 가슴 근육을 고립시켜 자극하는 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 풀오버',
    name_en: 'Dumbbell Pullover',
    category: 'chest' as const,
    equipment: 'dumbbell' as const,
    description: '벤치에 누워 덤벨을 머리 뒤로 내렸다가 올리며 가슴과 등을 동시에 자극하는 운동',
    primary_muscles: ['대흉근', '광배근'],
    secondary_muscles: ['삼두근', '전거근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '인클라인 바벨 벤치 프레스',
    name_en: 'Incline Barbell Bench Press',
    category: 'chest' as const,
    equipment: 'barbell' as const,
    description: '경사진 벤치에서 바벨을 밀어 올려 윗가슴을 집중적으로 발달시키는 운동',
    primary_muscles: ['대흉근 상부'],
    secondary_muscles: ['전면 삼각근', '삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '로우 케이블 플라이',
    name_en: 'Low Cable Fly',
    category: 'chest' as const,
    equipment: 'cable' as const,
    description: '낮은 위치의 케이블을 위로 당기며 가슴 상부와 중앙을 자극하는 운동',
    primary_muscles: ['대흉근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },

  // 등 (back) - 13개
  {
    name_ko: '바벨 로우',
    name_en: 'Barbell Row',
    category: 'back' as const,
    equipment: 'barbell' as const,
    description: '상체를 숙이고 바벨을 배꼽 쪽으로 당기며 등 두께를 키우는 운동',
    primary_muscles: ['광배근', '승모근'],
    secondary_muscles: ['후면 삼각근', '이두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 원암 로우',
    name_en: 'Dumbbell One-Arm Row',
    category: 'back' as const,
    equipment: 'dumbbell' as const,
    description: '벤치에 한 손과 무릎을 올리고 덤벨을 한 팔씩 당기는 등 운동',
    primary_muscles: ['광배근'],
    secondary_muscles: ['승모근', '후면 삼각근', '이두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '풀업',
    name_en: 'Pull-up',
    category: 'back' as const,
    equipment: 'bodyweight' as const,
    description: '철봉에 매달려 몸을 끌어올리는 등 너비를 키우는 최고의 운동',
    primary_muscles: ['광배근'],
    secondary_muscles: ['이두근', '승모근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '랫풀다운',
    name_en: 'Lat Pulldown',
    category: 'back' as const,
    equipment: 'machine' as const,
    description: '케이블 머신의 바를 가슴 쪽으로 당기며 광배근을 발달시키는 운동',
    primary_muscles: ['광배근'],
    secondary_muscles: ['이두근', '승모근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '시티드 케이블 로우',
    name_en: 'Seated Cable Row',
    category: 'back' as const,
    equipment: 'cable' as const,
    description: '앉아서 케이블을 배꼽 쪽으로 당기며 등 중앙부를 자극하는 운동',
    primary_muscles: ['광배근', '승모근'],
    secondary_muscles: ['후면 삼각근', '이두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '바벨 데드리프트',
    name_en: 'Barbell Deadlift',
    category: 'back' as const,
    equipment: 'barbell' as const,
    description: '바닥의 바벨을 들어올리며 전신을 강화하는 최고의 복합 운동',
    primary_muscles: ['척추기립근', '광배근', '대둔근', '햄스트링'],
    secondary_muscles: ['승모근', '전완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '페이스풀',
    name_en: 'Face Pull',
    category: 'back' as const,
    equipment: 'cable' as const,
    description: '케이블을 얼굴 쪽으로 당기며 후면 삼각근과 승모근을 자극하는 운동',
    primary_muscles: ['후면 삼각근', '승모근'],
    secondary_muscles: ['회전근개'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '티바 로우',
    name_en: 'T-Bar Row',
    category: 'back' as const,
    equipment: 'barbell' as const,
    description: '바벨 한쪽 끝을 고정하고 다른 쪽을 당기며 등 두께를 키우는 운동',
    primary_muscles: ['광배근', '승모근'],
    secondary_muscles: ['후면 삼각근', '이두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '친업',
    name_en: 'Chin-up',
    category: 'back' as const,
    equipment: 'bodyweight' as const,
    description: '언더그립(역수)으로 철봉에 매달려 몸을 끌어올리며 광배근과 이두근을 동시에 발달시키는 운동',
    primary_muscles: ['광배근', '이두근'],
    secondary_muscles: ['승모근', '전완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '바벨 슈러그',
    name_en: 'Barbell Shrug',
    category: 'back' as const,
    equipment: 'barbell' as const,
    description: '바벨을 잡고 어깨를 귀 쪽으로 으쓱하며 상부 승모근을 집중 발달시키는 운동',
    primary_muscles: ['상부 승모근'],
    secondary_muscles: ['견갑거근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 슈러그',
    name_en: 'Dumbbell Shrug',
    category: 'back' as const,
    equipment: 'dumbbell' as const,
    description: '양손에 덤벨을 들고 어깨를 귀 쪽으로 으쓱하며 상부 승모근을 발달시키는 운동',
    primary_muscles: ['상부 승모근'],
    secondary_muscles: ['견갑거근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '머신 로우',
    name_en: 'Machine Row',
    category: 'back' as const,
    equipment: 'machine' as const,
    description: '머신에 앉아 안정적인 자세로 등 근육을 당기며 발달시키는 운동',
    primary_muscles: ['광배근', '승모근'],
    secondary_muscles: ['후면 삼각근', '이두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '스트레이트 암 풀다운',
    name_en: 'Straight Arm Lat Pulldown',
    category: 'back' as const,
    equipment: 'cable' as const,
    description: '팔을 편 채로 케이블 바를 허벅지 쪽으로 당기며 광배근을 고립시키는 운동',
    primary_muscles: ['광배근'],
    secondary_muscles: ['대원근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },

  // 어깨 (shoulders) - 11개
  {
    name_ko: '바벨 오버헤드 프레스',
    name_en: 'Barbell Overhead Press',
    category: 'shoulders' as const,
    equipment: 'barbell' as const,
    description: '서서 바벨을 머리 위로 밀어 올리는 어깨 운동의 기본 종목',
    primary_muscles: ['전면 삼각근', '측면 삼각근'],
    secondary_muscles: ['삼두근', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 숄더 프레스',
    name_en: 'Dumbbell Shoulder Press',
    category: 'shoulders' as const,
    equipment: 'dumbbell' as const,
    description: '앉거나 서서 덤벨을 머리 위로 밀어 올리는 어깨 운동',
    primary_muscles: ['전면 삼각근', '측면 삼각근'],
    secondary_muscles: ['삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '사이드 레터럴 레이즈',
    name_en: 'Side Lateral Raise',
    category: 'shoulders' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 옆으로 들어올려 어깨 측면 삼각근을 집중 발달시키는 운동',
    primary_muscles: ['측면 삼각근'],
    secondary_muscles: ['승모근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '프론트 레이즈',
    name_en: 'Front Raise',
    category: 'shoulders' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 앞으로 들어올려 전면 삼각근을 자극하는 운동',
    primary_muscles: ['전면 삼각근'],
    secondary_muscles: ['측면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '리어 델트 플라이',
    name_en: 'Rear Delt Fly',
    category: 'shoulders' as const,
    equipment: 'dumbbell' as const,
    description: '상체를 숙이고 덤벨을 양옆으로 벌려 후면 삼각근을 자극하는 운동',
    primary_muscles: ['후면 삼각근'],
    secondary_muscles: ['승모근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '업라이트 로우',
    name_en: 'Upright Row',
    category: 'shoulders' as const,
    equipment: 'barbell' as const,
    description: '바벨을 턱 아래까지 끌어올리며 측면 삼각근과 승모근을 자극하는 운동',
    primary_muscles: ['측면 삼각근', '승모근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '아놀드 프레스',
    name_en: 'Arnold Press',
    category: 'shoulders' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 회전시키며 프레스하여 어깨 전체를 자극하는 운동',
    primary_muscles: ['전면 삼각근', '측면 삼각근'],
    secondary_muscles: ['삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '케이블 레터럴 레이즈',
    name_en: 'Cable Lateral Raise',
    category: 'shoulders' as const,
    equipment: 'cable' as const,
    description: '케이블을 옆으로 들어올려 지속적인 긴장으로 측면 삼각근을 발달시키는 운동',
    primary_muscles: ['측면 삼각근'],
    secondary_muscles: ['승모근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '머신 숄더 프레스',
    name_en: 'Machine Shoulder Press',
    category: 'shoulders' as const,
    equipment: 'machine' as const,
    description: '머신을 이용해 안정적으로 어깨 전체를 밀어 올리며 발달시키는 운동',
    primary_muscles: ['전면 삼각근', '측면 삼각근'],
    secondary_muscles: ['삼두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '파이크 푸시업',
    name_en: 'Pike Push-up',
    category: 'shoulders' as const,
    equipment: 'bodyweight' as const,
    description: '엉덩이를 높이 들고 거꾸로 된 V자 자세에서 머리 쪽으로 밀어 올리는 맨몸 어깨 운동',
    primary_muscles: ['전면 삼각근'],
    secondary_muscles: ['삼두근', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '케이블 리어 델트 플라이',
    name_en: 'Cable Rear Delt Fly',
    category: 'shoulders' as const,
    equipment: 'cable' as const,
    description: '케이블을 교차하여 양옆으로 당기며 후면 삼각근을 자극하는 운동',
    primary_muscles: ['후면 삼각근'],
    secondary_muscles: ['승모근', '능형근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },

  // 팔 (arms) - 12개
  {
    name_ko: '바벨 컬',
    name_en: 'Barbell Curl',
    category: 'arms' as const,
    equipment: 'barbell' as const,
    description: '바벨을 들어올리며 이두근을 발달시키는 가장 기본적인 팔 운동',
    primary_muscles: ['이두근'],
    secondary_muscles: ['전완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 컬',
    name_en: 'Dumbbell Curl',
    category: 'arms' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 번갈아가며 들어올려 이두근을 자극하는 운동',
    primary_muscles: ['이두근'],
    secondary_muscles: ['전완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '해머 컬',
    name_en: 'Hammer Curl',
    category: 'arms' as const,
    equipment: 'dumbbell' as const,
    description: '손바닥이 마주보게 덤벨을 들어올려 상완근과 전완근을 발달시키는 운동',
    primary_muscles: ['상완근', '전완근'],
    secondary_muscles: ['이두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '트라이셉 딥스',
    name_en: 'Tricep Dips',
    category: 'arms' as const,
    equipment: 'bodyweight' as const,
    description: '벤치나 평행봉에 손을 짚고 몸을 낮췄다 올리며 삼두근을 자극하는 운동',
    primary_muscles: ['삼두근'],
    secondary_muscles: ['대흉근 하부', '전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '케이블 푸시다운',
    name_en: 'Cable Pushdown',
    category: 'arms' as const,
    equipment: 'cable' as const,
    description: '케이블을 아래로 밀어내리며 삼두근을 집중 자극하는 운동',
    primary_muscles: ['삼두근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '오버헤드 트라이셉 익스텐션',
    name_en: 'Overhead Tricep Extension',
    category: 'arms' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 머리 위로 들어올렸다가 내리며 삼두근 장두를 자극하는 운동',
    primary_muscles: ['삼두근 장두'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '프리처 컬',
    name_en: 'Preacher Curl',
    category: 'arms' as const,
    equipment: 'barbell' as const,
    description: '프리처 벤치에 팔을 고정하고 바벨을 들어올려 이두근을 고립시키는 운동',
    primary_muscles: ['이두근'],
    secondary_muscles: ['전완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '클로즈그립 벤치 프레스',
    name_en: 'Close-Grip Bench Press',
    category: 'arms' as const,
    equipment: 'barbell' as const,
    description: '좁은 그립으로 벤치 프레스를 하며 삼두근을 집중 발달시키는 운동',
    primary_muscles: ['삼두근'],
    secondary_muscles: ['대흉근', '전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '컨센트레이션 컬',
    name_en: 'Concentration Curl',
    category: 'arms' as const,
    equipment: 'dumbbell' as const,
    description: '벤치에 앉아 팔꿈치를 허벅지 안쪽에 고정하고 덤벨을 들어올려 이두근을 고립시키는 운동',
    primary_muscles: ['이두근'],
    secondary_muscles: ['상완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '케이블 컬',
    name_en: 'Cable Curl',
    category: 'arms' as const,
    equipment: 'cable' as const,
    description: '케이블을 이용해 지속적인 긴장 하에 이두근을 수축시키는 운동',
    primary_muscles: ['이두근'],
    secondary_muscles: ['전완근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '스컬 크러셔',
    name_en: 'Skull Crusher',
    category: 'arms' as const,
    equipment: 'barbell' as const,
    description: '벤치에 누워 바벨을 이마 위에서 굽혔다 펴며 삼두근을 집중 자극하는 운동',
    primary_muscles: ['삼두근'],
    secondary_muscles: ['전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '리스트 컬',
    name_en: 'Wrist Curl',
    category: 'arms' as const,
    equipment: 'barbell' as const,
    description: '바벨을 손목만으로 말아올려 전완근을 집중 발달시키는 운동',
    primary_muscles: ['전완근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },

  // 하체 (legs) - 18개
  {
    name_ko: '바벨 백 스쿼트',
    name_en: 'Barbell Back Squat',
    category: 'legs' as const,
    equipment: 'barbell' as const,
    description: '바벨을 어깨에 올리고 앉았다 일어서는 하체 운동의 왕',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['햄스트링', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '프론트 스쿼트',
    name_en: 'Front Squat',
    category: 'legs' as const,
    equipment: 'barbell' as const,
    description: '바벨을 앞쪽 어깨에 올리고 스쿼트하여 대퇴사두근을 집중 자극하는 운동',
    primary_muscles: ['대퇴사두근'],
    secondary_muscles: ['대둔근', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '레그 프레스',
    name_en: 'Leg Press',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '머신에 앉아 발판을 밀어내며 하체 전체를 안전하게 발달시키는 운동',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['햄스트링'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '레그 컬',
    name_en: 'Leg Curl',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '머신에 엎드려 다리를 구부리며 햄스트링을 집중 자극하는 운동',
    primary_muscles: ['햄스트링'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '레그 익스텐션',
    name_en: 'Leg Extension',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '머신에 앉아 다리를 펴며 대퇴사두근을 고립시키는 운동',
    primary_muscles: ['대퇴사두근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '루마니안 데드리프트',
    name_en: 'Romanian Deadlift',
    category: 'legs' as const,
    equipment: 'barbell' as const,
    description: '바벨을 잡고 상체를 숙였다 일으키며 햄스트링을 집중 발달시키는 운동',
    primary_muscles: ['햄스트링', '대둔근'],
    secondary_muscles: ['척추기립근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 루마니안 데드리프트',
    name_en: 'Dumbbell Romanian Deadlift',
    category: 'legs' as const,
    equipment: 'dumbbell' as const,
    description: '양손에 덤벨을 들고 상체를 숙였다 일으키며 햄스트링과 둔근을 발달시키는 운동',
    primary_muscles: ['햄스트링', '대둔근'],
    secondary_muscles: ['척추기립근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '불가리안 스플릿 스쿼트',
    name_en: 'Bulgarian Split Squat',
    category: 'legs' as const,
    equipment: 'dumbbell' as const,
    description: '한 발을 벤치에 올리고 스쿼트하며 한쪽 다리씩 집중 발달시키는 운동',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['햄스트링'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '힙 쓰러스트',
    name_en: 'Hip Thrust',
    category: 'legs' as const,
    equipment: 'barbell' as const,
    description: '등을 벤치에 기대고 바벨을 골반에 올려 엉덩이를 들어올리는 대둔근 운동',
    primary_muscles: ['대둔근'],
    secondary_muscles: ['햄스트링'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '카프 레이즈',
    name_en: 'Calf Raise',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '발꿈치를 들어올려 종아리 근육을 발달시키는 운동',
    primary_muscles: ['비복근', '가자미근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '런지',
    name_en: 'Lunge',
    category: 'legs' as const,
    equipment: 'bodyweight' as const,
    description: '한 발을 앞으로 내디디며 앉았다 일어서는 하체 전체 운동',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['햄스트링', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '덤벨 런지',
    name_en: 'Dumbbell Lunge',
    category: 'legs' as const,
    equipment: 'dumbbell' as const,
    description: '양손에 덤벨을 들고 한 발을 앞으로 내디디며 하체 전체를 강화하는 중량 런지 운동',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['햄스트링', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '핵 스쿼트',
    name_en: 'Hack Squat',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '핵 스쿼트 머신에서 등을 기대고 다리를 밀어 올리며 대퇴사두근을 집중 발달시키는 운동',
    primary_muscles: ['대퇴사두근'],
    secondary_muscles: ['대둔근', '햄스트링'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '시티드 카프 레이즈',
    name_en: 'Seated Calf Raise',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '앉은 자세에서 발꿈치를 들어올려 가자미근을 집중적으로 발달시키는 운동',
    primary_muscles: ['가자미근'],
    secondary_muscles: ['비복근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '고블릿 스쿼트',
    name_en: 'Goblet Squat',
    category: 'legs' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 가슴 앞에 들고 스쿼트하며 하체와 코어를 동시에 강화하는 초보자 친화적 운동',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '스텝업',
    name_en: 'Step-up',
    category: 'legs' as const,
    equipment: 'dumbbell' as const,
    description: '덤벨을 들고 높은 박스나 벤치 위로 올라서며 한쪽 다리씩 강화하는 운동',
    primary_muscles: ['대퇴사두근', '대둔근'],
    secondary_muscles: ['햄스트링'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '힙 어덕션',
    name_en: 'Hip Adduction',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '머신에 앉아 다리를 안쪽으로 모으며 허벅지 안쪽 내전근을 강화하는 운동',
    primary_muscles: ['내전근'],
    secondary_muscles: ['대둔근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '힙 어브덕션',
    name_en: 'Hip Abduction',
    category: 'legs' as const,
    equipment: 'machine' as const,
    description: '머신에 앉아 다리를 바깥쪽으로 벌리며 엉덩이 옆 근육을 강화하는 운동',
    primary_muscles: ['중둔근', '소둔근'],
    secondary_muscles: ['대둔근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },

  // 코어 (core) - 9개
  {
    name_ko: '플랭크',
    name_en: 'Plank',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '엎드린 자세로 몸을 일직선으로 유지하며 코어 전체를 강화하는 운동',
    primary_muscles: ['복직근', '복횡근'],
    secondary_muscles: ['척추기립근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '크런치',
    name_en: 'Crunch',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '누워서 상체를 말아올리며 복직근을 집중 자극하는 운동',
    primary_muscles: ['복직근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '행잉 레그 레이즈',
    name_en: 'Hanging Leg Raise',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '철봉에 매달려 다리를 들어올리며 하복부를 강화하는 운동',
    primary_muscles: ['복직근 하부', '장요근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '러시안 트위스트',
    name_en: 'Russian Twist',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '앉은 자세에서 상체를 좌우로 회전하며 복사근을 자극하는 운동',
    primary_muscles: ['복사근'],
    secondary_muscles: ['복직근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '케이블 우드칩',
    name_en: 'Cable Woodchop',
    category: 'core' as const,
    equipment: 'cable' as const,
    description: '케이블을 대각선으로 당기며 코어 회전력을 강화하는 운동',
    primary_muscles: ['복사근', '복직근'],
    secondary_muscles: [],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '사이드 플랭크',
    name_en: 'Side Plank',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '옆으로 누워 한 팔로 몸을 지탱하며 측면 코어를 강화하는 운동',
    primary_muscles: ['복사근'],
    secondary_muscles: ['중둔근', '코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '바이시클 크런치',
    name_en: 'Bicycle Crunch',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '누워서 자전거 페달을 밟듯 팔꿈치와 반대쪽 무릎을 번갈아 모으며 복근 전체를 자극하는 운동',
    primary_muscles: ['복직근', '복사근'],
    secondary_muscles: ['장요근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '데드 버그',
    name_en: 'Dead Bug',
    category: 'core' as const,
    equipment: 'bodyweight' as const,
    description: '누운 자세에서 팔과 다리를 번갈아 뻗으며 코어 안정성을 강화하는 운동',
    primary_muscles: ['복횡근'],
    secondary_muscles: ['복직근', '장요근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '에이비 롤아웃',
    name_en: 'Ab Rollout',
    category: 'core' as const,
    equipment: 'other' as const,
    description: '에이비 휠을 잡고 몸을 앞으로 굴려 나갔다 당기며 코어 전체를 강화하는 운동',
    primary_muscles: ['복직근', '복횡근'],
    secondary_muscles: ['광배근', '전면 삼각근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },

  // 유산소 (cardio) - 8개
  {
    name_ko: '러닝',
    name_en: 'Running',
    category: 'cardio' as const,
    equipment: 'other' as const,
    description: '달리기를 통해 심폐지구력을 향상시키고 칼로리를 소모하는 유산소 운동',
    primary_muscles: ['심폐지구력'],
    secondary_muscles: ['하체'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '사이클링',
    name_en: 'Cycling',
    category: 'cardio' as const,
    equipment: 'machine' as const,
    description: '자전거를 타며 하체를 강화하고 심폐지구력을 향상시키는 유산소 운동',
    primary_muscles: ['심폐지구력', '대퇴사두근'],
    secondary_muscles: ['햄스트링', '대둔근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '로잉 머신',
    name_en: 'Rowing Machine',
    category: 'cardio' as const,
    equipment: 'machine' as const,
    description: '노젓기 동작으로 전신을 사용하며 심폐지구력과 근력을 동시에 향상시키는 운동',
    primary_muscles: ['심폐지구력', '광배근', '대퇴사두근'],
    secondary_muscles: ['전신'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '줄넘기',
    name_en: 'Jump Rope',
    category: 'cardio' as const,
    equipment: 'other' as const,
    description: '줄넘기를 통해 심폐지구력과 협응력을 향상시키는 고강도 유산소 운동',
    primary_muscles: ['심폐지구력'],
    secondary_muscles: ['하체', '어깨'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '스텝퍼',
    name_en: 'Stair Climber',
    category: 'cardio' as const,
    equipment: 'machine' as const,
    description: '계단 오르기 머신으로 하체를 강화하며 심폐지구력을 향상시키는 유산소 운동',
    primary_muscles: ['대둔근', '대퇴사두근'],
    secondary_muscles: ['햄스트링', '비복근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '일립티컬',
    name_en: 'Elliptical',
    category: 'cardio' as const,
    equipment: 'machine' as const,
    description: '타원형 궤도의 머신을 이용해 관절 부담 없이 전신 유산소 운동을 하는 저충격 운동',
    primary_muscles: ['전신'],
    secondary_muscles: ['코어'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '버피',
    name_en: 'Burpee',
    category: 'cardio' as const,
    equipment: 'bodyweight' as const,
    description: '스쿼트, 푸시업, 점프를 연결하여 전신을 사용하는 고강도 유산소 운동',
    primary_muscles: ['전신'],
    secondary_muscles: ['코어', '심폐지구력'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
  {
    name_ko: '마운틴 클라이머',
    name_en: 'Mountain Climber',
    category: 'cardio' as const,
    equipment: 'bodyweight' as const,
    description: '플랭크 자세에서 무릎을 번갈아 가슴 쪽으로 당기며 코어와 심폐지구력을 강화하는 운동',
    primary_muscles: ['코어', '장요근'],
    secondary_muscles: ['전면 삼각근', '대퇴사두근'],
    icon_name: 'dumbbell',
    is_custom: false,
  },
];
